services:

  # MySQL untuk users-db (port 3307)
  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: users_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3317:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      retries: 5
    networks:
      - app-net

  # MySQL untuk orders-db (port 3308)
  mysql-orders:
    image: mysql:8.0
    container_name: mysql-orders
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: orders_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3318:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      retries: 5
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
